# Generated by Django 4.1.5 on 2023-04-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormData',
            new_name='Form',
        ),
    ]
